### ISSUE TITLE
Make the default message "Away" instead of "Busy"

### ISSUE THREAD

**Issue by robhruska** [robhruska/CalendarToSlack#3]
"Busy" sounds so formal and stuffy. "Away", though redundant, sounds better.

**Comment by jessehudl** [comment]
I agree. It's also not totally redundant IMO since being set to away could be for many reasons (e.g. being idle, manually setting and forgetting to put it back) whereas actually having it your name gives the impression that you set it there because you are in fact away doing something else.

**Comment by robhruska** [comment]
Yeah, that makes a lot of sense. Thanks for the suggestion!
